<footer class="site-footer">
	<h2 class="accessibility"></h2>
	<div class="footer-menu">
		<nav class="navigation  navigation--footer">
			<ul id="menu-footer-menu" class="footer-menu  nav  nav--main">
				<li id="menu-item-10026"
					class="menu-item menu-item-type-custom menu-item-object-custom menu-item-10026"><a
					href="{{url('/')}}">Khám
						phá những ưu đãi độc quyền tại meramera.vn ngay!</a></li>
			</ul>
		</nav>
	</div>
	<div class="copyright-text">
		<span>Copyright © 2015 meramera.vn</span>
	</div>
</footer>
<!-- .site-footer -->
</div>
<!-- .container -->
</div>
<!-- .wrapper -->
<!-- Starting of Javascript Generated by Simple Slideshow Manager -->
<script type="text/javascript">
</script>
<!-- Ending of Javascript Generated by Advanced Slideshow Manager -->
<div style="display: none"></div>
</body>
 
</html>